CREATE TABLE IF NOT EXISTS indexer.network_nodes (
  id                    VARCHAR(66)   PRIMARY KEY,
  item_id               VARCHAR(20)   NOT NULL,
  tenant                TEXT          NOT NULL,
  type_id               BIGINT        NOT NULL,
  owner_cap_id          VARCHAR(66)   NOT NULL,
  location              VARCHAR(66)   NOT NULL,
  status                TEXT          NOT NULL,
  energy_production     BIGINT        NOT NULL,
  energy_capacity       BIGINT        NOT NULL,
  energy_reserved       BIGINT        NOT NULL,
  connected_ids         TEXT[]        NOT NULL,
  burning               BOOLEAN       NOT NULL,
  burn_rate             BIGINT        NOT NULL,
  burn_start            TIMESTAMPTZ   NOT NULL,
  burn_updated          TIMESTAMPTZ   NOT NULL,
  burn_elapsed          BIGINT        NOT NULL,
  fuel_capacity         BIGINT        NOT NULL,
  fuel_quantity         BIGINT        NOT NULL,
  fuel_type             BIGINT,
  fuel_volume           BIGINT,
  name                  TEXT,
  description           TEXT,
  url                   TEXT,
  checkpoint_updated    BIGINT        NOT NULL
);
